medispring/icc-api

icc-api/model/HealthcarePartyDto.ts

from @vpi-b12 
ajout du userId dans hcp : https://www.pivotaltracker.com/story/show/161376510

ajout du userId dans hcp

---

icc-api/iccApi.ts
icc-x-api/icc-crypto-x-api.ts
package.json
tsconfig.json

Cette PR permet l'utilisation du module via NPM. Elle contient deux changements à l'icc-x-api:
- Résolution d'un problème de typage statique dans l'API crypto.
- Export de XHR.

NPM module

---

icc-api/api/iccMessageApi.ts

See https://github.com/antoinepairet/icure-backend/pull/55

update icc following antoinepairet/icure-backend#55

---

icc-x-api/icc-crypto-x-api.ts
icc-x-api/icc-invoice-x-api.ts

Reverts antoinepairet/icc-api#64

Revert "Add a parameter to do not get invoices from the parent hcparty"

---

icc-api/api/iccClassificationApi.ts
icc-x-api/icc-crypto-x-api.ts
icc-x-api/icc-patient-x-api.ts

Needs : https://github.com/antoinepairet/icure-backend/pull/66

Make the share method more resilient and a bit more readable

---

icc-api/model/FrontEndMigrationDto.ts

Needs : antoinepairet/icure-backend#66

Add processCount on frontEndMigrationDto

---

icc-x-api/icc-message-x-api.ts

See https://github.com/antoinepairet/medispring/issues/1684

Add year in efact entity ref

---

icc-x-api/icc-invoice-x-api.ts
icc-x-api/icc-message-x-api.ts

This fixes a bug in the EntityReference sequence numbers

fix sequence numbers (EntityReference)

---

icc-x-api/icc-message-x-api.ts

This fixes :
- Efact error parsing
- FHC error handling

 Fix error detection eFact

---

icc-api/model/FlowItemDto.ts

Reverts antoinepairet/icc-api#100

Revert "Revert "add undeclared dto field to FlowItemDto""

---

icc-x-api/icc-message-x-api.ts

Fixes https://github.com/antoinepairet/medispring/issues/1953

Block efact message creating for timeout or failed to fetch

---

icc-x-api/icc-message-x-api.ts

* If several messages have the same transport GUID, match the fileReference (uuidBase36Half encoding) to determine the correct message. This situation can arrive when sending batches while the efact numseq counter is not correct... 
An other PR in medispring should be created to prevent such situation (blocking error)
* Do not update the status of the message when receiving a 920098 with some error => otherwise, it is not possible to differentiate batch completed (920900 + error) from (920098 + error). Currently, the batch is in status "Partially accepted" after receiving the 920098.
**To be deployed asap**

eFact improvements - URGENT

---

icc-api/api/iccUserApi.ts

This fixes the bad return value on the method findByHcparty
See https://github.com/antoinepairet/icure-backend/pull/84

Fix method findByHcparty

---

icc-api/model/EntityTemplateDto.ts

See https://github.com/antoinepairet/icure-backend/pull/85

Add a field subtype in entitytemplate

---

icc-api/model/MedicalLocationDto.ts

See MED-53
Related : https://github.com/antoinepairet/icure-backend/pull/88

add agendaIds in MedicalLocation

---

icc-x-api/icc-calendar-item-x-api.ts
icc-x-api/icc-contact-x-api.ts
icc-x-api/icc-crypto-x-api.ts

Commented out multiple methods to add further analysis
Signed-off-by: esteban <esteban@medispring.be>

MS-830 Replace calendarItem.patientId direct link by cryptedForeignKeys.

---

icc-x-api/icc-calendar-item-x-api.ts

remove the delegations' object in a CalendarItem

MS-830 Added resetCalendarDelegationObjects() method to

---

icc-api/model/PatientDto.ts

https://medispring.atlassian.net/browse/MS-871

MS-871 Add nonDuplicateIds property to PatientDto

---

icc-api/api/iccHelementApi.ts

Add filtering support for health elements.

[MS-1484] Add a filterBy endpoint on the health elements REST API

---

icc-x-api/icc-crypto-x-api.ts

- added documentation for some of the methods
- review and added TODOs 
- light refactoring (renamed variables, extracted methods)

Refactoring icc-x-api

---

icc-api/api/iccContactApi.ts
icc-x-api/icc-contact-x-api.ts

[x] require icure-backend https://github.com/medispring/icure-backend/pull/157 PR to be merged.

MS-1633 Filter contacts by multiple foreign keys

---

icc-x-api/icc-bekmehr-x-api.ts

MS-2246 export patient data in a PMF file

---

icc-x-api/crypto/utils.ts
icc-x-api/icc-contact-x-api.ts
icc-x-api/icc-crypto-x-api.ts
test/crypto-utils.ts

This concerns `TypedArray`-related changes and should speed up the code somewhat in addition to being less copy-intensive.
A couple of notes:
* I added unit tests for the null truncation but I have no idea how the typescript tests are supposed to be compiled for Mocha. I compiled and ran the tests manually to check that they pass, but it would be good to clarify the testing process.
* I bypassed Prettier on `icc-contact-x-api.ts` to avoid committing off-topic formatting changes. Maybe the whole codebase should be reformatted at some point in coordination with upstream?

Crypto optimizations

---

icc-x-api/icc-accesslog-x-api.ts

**Do not merge before this icure-backend fix is deployed everywhere** https://github.com/medispring/icure-backend/pull/189

MS-2933: fix redundant access log pagination calls

---

icc-x-api/icc-bekmehr-x-api.ts
icc-x-api/icc-message-x-api.ts

See https://github.com/Microsoft/TypeScript/issues/299

Fixed issue with typing

---

icc-x-api/icc-crypto-x-api.ts

Companion PR to the main MS-4345 PR https://github.com/medispring/medispring/pull/3962

MS-4345 fix eHealth certificate sync

---

icc-api/api/iccUserApi.ts
icc-api/model/MedicationSchemeExportInfoDto.ts

https://medispring.atlassian.net/browse/MS-5071

[MS-5071] restore user matches

---

icc-api/api/iccMessageApi.ts
icc-api/api/iccUserApi.ts
icc-api/model/InvoiceItem.ts
icc-api/model/UserDto.ts
icc-api/model/UserStubDto.ts
icc-x-api/utils/efact-util.ts

Update icc api with genloc from icure taktik

---

icc-x-api/crypto/utils.ts

MS-5019 import dependency in order to fix unit tests

Add dependency to make tests work
